blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions / Q&A
    url: https://github.com/hundert1/alert-tinder/discussions
    about: Allgemeine Fragen, Ideen, Feedback, das nicht in Bug-Report oder Feature-Request passt.
